### PR TITLE
[1.0 -> main] Better logging for aggregate_vote failure and add logging for proposer policy becoming active

### PR DESCRIPTION
**Pull request by linh2931**
* Log detailed information when verify_sig fails, including block ID, vote strong or weak.
* Add debug logging when  proposer policy becoming active
```
debug 2024-08-15T12:53:57.365 unit_test block_header_state.cpp:349    finish_next          ] Proposer  policy version change: 0 -> 2
debug 2024-08-15T12:53:57.365 unit_test block_header_state.cpp:351    finish_next          ] New       proposer policy becoming active in block 37:                                                           0000002553a993a7e5895478dd02d8b67716476ca7df7cd78cf221752787f233: {"proposal_time":"2020-  01-01T00:00:11.500","proposer_schedule":{"version":2,"producers":[{"producer_name":"bob",  "authority":[0,         {"threshold":1,"keys":[{"key":                                                                         "EOS5mF6KuJY8NgNqzKS4oUjoq2q6n3txkprAhtjLb1gyi7nJ7QZLD","weight":1}]}]}]}}
```

### CODE REVIEW

**Review by arhag — CHANGES_REQUESTED** [review]
This appears to be a cherry-pick of the commits since they are new commit hashes.

We need the forwarding PR to bring the actual commits from `release/1.0`.

**Comment by linh2931** [comment]
> This appears to be a cherry-pick of the commits since they are new commit hashes.
> 
> We need the forwarding PR to bring the actual commits from `release/1.0`.

I used `git merge` from the `release/1.0` branch initially. But that brought in commits from Kevin's PR. Is that OK?

**Comment by arhag** [comment]
Yes, because after https://github.com/AntelopeIO/spring/pull/554 is merged in, those commits will disappear.

**Comment by linh2931** [comment]
> Yes, because after #554 is merged in, those commits will disappear.

Thanks. Will create a new PR.

**Pull request closed without merging**
