### PR TITLE
Remove `finality` directories.

### PR DESCRIPTION
**Pull request by greg7mdp**
We had `finality` directories in `libraries/chain` and `libraries/chain/include/eosio/chain`, however these were inconsistently used and were not proven to be useful. This PR removes these subdirectories and moves the files one level up.

### CODE REVIEW

**Review by linh2931 — APPROVED** [review]
I don't have strong feeling on if or not we should have a separate directory for `finality`. We do have a separate `webassmbly` under `chain`.

**Review by heifner — APPROVED** [review]
Don't really see the point, but this is fine I guess.

**Comment by greg7mdp** [comment]
@areg, what do you think?

**Comment by ericpassmore** [comment]
Note:start
category: Chores
component: Internal
summary: Remove unused finality directories under `libraries `.
Note:end

**Comment by greg7mdp** [comment]
Didn't get a very enthusiastic response to this PR. 
I'm OK tabling it if someone prefers having the `finality` directories as today, if so just let me know. 
Otherwise I'll probably merge it later this evening.

**Pull request merged**
